config/routes.rb
Rails.application.routes.draw do
  
  namespace :staging do
    get 'bill_view/empty_bill'
  end

  resources :invoices
  resources :items

  root 'welcome#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
    has_many :orders
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_relationships
  has_many :sub_items, :through => :item_relationships
  has_many :orders

  def parent
    ItemRelationship.where(sub_item: self).first.try(:item)      
  end
end

app/models/item_relationship.rb
class ItemRelationship < ActiveRecord::Base
  belongs_to :item
  belongs_to :sub_item, :class_name => 'Item'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    respond_to :html
    before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  
    def index
        @invoices = Invoice.all
        @invoices = @invoices.starts_with(params[:starts_with]) if params[:starts_with].present?
        respond_with(@invoices)
    end 

    def show
        respond_with(@invoice)
    end

    def new
        @invoice = Invoice.create
        session[:current_invoice] = @invoice.id
        respond_with(@invoice)
    end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def item_params
      params[:invoice]
    end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = Item.all
    @items = @items.starts_with(params[:starts_with]) if params[:starts_with].present?
    respond_with(@items)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def show
    if (@item.sub_items.length == 0) 
      invoice_id = session[:current_invoice_id]
      @invoice = Invoice.where(id: invoice_id).first
      redirect_to root_path
    else
      respond_with(@item)
    end
  end




  
  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params[:item]
    end

end

app/controllers/staging/bill_view_controller.rb
require 'ostruct'

class Staging::BillViewController < ApplicationController
  layout "staging/invoice"

  def empty_bill
    @invoice = OpenStruct.new
    @invoice.serial_number = 1
    @invoice.date = DateTime.current

    order = OpenStruct.new
    order.description = "Coffee"
    order.rate = 5.00
    order.quantity = 2
    @invoice.orders = [order]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def display_price_indian(amount)
        number_to_currency(amount, 
            unit: raw("&#x20b9;"),
            separator: ".", 
            delimiter: "", 
            format: "%u %n")
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/staging/bill_view_helper.rb
module Staging::BillViewHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/list.html.haml
%h1 Invoices#list
%p Find me in app/views/invoices/list.html.haml

app/views/invoices/show.html.haml
%h1 Invoice

%article
  %h1 Recipient
  %address
    %p
      Vidyasagar<br/>
      1, Ranjith Road, Kotturpuram<br/>
      Chennai – 600 085.<br/>
  %table.meta
    %tr
      %th
        %span Invoice #
      %td
        %span 
          = @invoice.id
    %tr
      %th
        %span Date
      %td
        %span 
          = @invoice.created_at.strftime("%F")
    
  %table.inventory
    %col
    %col
    %col
    %col
    %thead
      %tr
        %th
          %span Description
        %th
          %span Price
        %th
          %span Qty
        %th
          %span Amount
    %tbody
      - @invoice.orders.each do |order|
        %tr
          %td
            %span= order.item.name
          %td
            %span= display_price_indian(order.item.price)              
          %td
            %span= order.quantity
          %td
            %span= display_price_indian(order.item.price * order.quantity)
          - total_amount += order.item.price
    %tfoot
      %tr
        %td
          %span Total
        %td
        %td
        %td
          %span= display_price_indian(total_amount)

app/views/items/_item_view.html.haml
- if item.present?
  %h2.centered
    = link_to (item.name), item
  = audio_tag(item.audio_clip, controls: false)

app/views/items/index.html.haml
%p#notice= notice
%h1 Listing Items
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Item', new_item_path

app/views/items/show.html.haml
= javascript_tag do
  window.items =
  = raw @item.sub_items.to_json(:only => [ :id ])
  

.row
  .large-12.columns
    %h1.underline
      = @item.name


.row
  .large-2.columns
    %h3.subheader
      Go back
  .large-10.columns.item
    .panel
      = render partial: 'item_view', object: @item.parent, as: 'item'
      
.flex
  - @item.sub_items.each do |i|
    .panel
      = render partial: 'item_view', object: i, as: 'item'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Aura Bill Generator"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag "application"

app/views/layouts/backup-app.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuraBill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/backup-app.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AuraBill
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/staging/invoice.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Aura Bill Generator"
    = stylesheet_link_tag "staging/bill_view"
    = javascript_include_tag "vendor/invoice-script"
    = csrf_meta_tags
  %body
    = yield

app/views/staging/bill_view/empty_bill.html.haml
%article
  %h1 Recipient
  %address
    %p
      Vidyasagar<br/>
      1, Ranjith Road, Kotturpuram<br/>
      Chennai – 600 085.<br/>
  %table.meta
    %tr
      %th
        %span Invoice #
      %td
        %span 
          = @invoice.serial_number
    %tr
      %th
        %span Date
      %td
        %span 
          = @invoice.date.strftime("%F")
    
  %table.inventory
    %col
    %col
    %col
    %col
    %thead
      %tr
        %th
          %span Description
        %th
          %span Rate
        %th
          %span Quantity
        %th
          %span Price
    %tbody
      - @invoice.orders.each do |order|
        %tr
          %td
            %span= order.description
          %td
            %span= number_to_currency(order.rate)
          %td
            %span= order.quantity
          %td
            %span= number_to_currency(order.rate * order.quantity)
    %tfoot
      %tr
        %td
          %span Total
        %td
        %td
        %td
          %span 0.00
   
  / %table.balance
  /   %tr
  /     %th
  /       %span Total
  /     %td
  /       %span{"data-prefix" => ""} $
  /       %span 600.00
  /   %tr
  /     %th
  /       %span Amount Paid
  /     %td
  /       %span{"data-prefix" => ""} $
  /       %span 0.00
  /   %tr
  /     %th
  /       %span Balance Due
  /     %td
  /       %span{"data-prefix" => ""} $
  /       %span 600.00

app/views/welcome/index.html.haml
.row
  .columns.large-12
    %h1 Aura Bill Generator

.row
  .columns.large-12
    = link_to "Main Menu", item_path(Item.where(name: 'Menu').first)